import { useState } from "react";

export default function JsonViewer({ data }) {
  const [copied, setCopied] = useState(false);

  if (!data) return null;

  const json = JSON.stringify(data, null, 2);

  const copyJson = async () => {
    await navigator.clipboard.writeText(json);
    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 2000);
  };

  const downloadJson = () => {
    const blob = new Blob([json], {
      type: "application/json",
    });

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;
    a.download = "candidate-output.json";

    a.click();

    URL.revokeObjectURL(url);
  };

  return (
    <section className="mt-10 rounded-3xl border bg-white p-8 shadow-lg">

      <div className="flex items-center justify-between">

        <div>

          <h2 className="text-2xl font-bold">
            Canonical Output JSON
          </h2>

          <p className="mt-2 text-slate-500">
            Final projected candidate profile generated by the
            transformation pipeline.
          </p>

        </div>

        <div className="flex gap-3">

          <button
            onClick={copyJson}
            className="rounded-xl bg-slate-800 px-5 py-3 text-white hover:bg-slate-900"
          >
            {copied ? "Copied ✓" : "Copy JSON"}
          </button>

          <button
            onClick={downloadJson}
            className="rounded-xl bg-blue-600 px-5 py-3 text-white hover:bg-blue-700"
          >
            Download JSON
          </button>

        </div>

      </div>

      <pre className="mt-8 max-h-[500px] overflow-auto rounded-2xl bg-slate-900 p-6 text-sm text-green-400">
{json}
      </pre>

    </section>
  );
}